# Generated by Django 5.0.14 on 2025-07-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(help_text='Describe your custom project needs')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
