# Generated by Django 5.0.14 on 2025-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_custompackagerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompackagerequest',
            name='message',
            field=models.TextField(),
        ),
    ]
