# Generated by Django 5.0.14 on 2025-07-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_stripe_id'),
        ('orders', '0006_remove_order_billing_address_and_more'),
    ]

    operations = [
    ]
